echo | FE45_Compress.exe ../graphics/13YearsLater.bin
echo | FE45_Compress.exe ../graphics/Arena.bin
echo | FE45_Compress.exe ../graphics/BattleStats.bin
echo | FE45_Compress.exe ../graphics/BattleStatsLevelIncluded.bin
echo | FE45_Compress.exe ../graphics/InventoryBrownBars.bin
echo | FE45_Compress.exe ../graphics/InventoryBrownBarsTilemap1.bin
echo | FE45_Compress.exe ../graphics/InventoryBrownBarsTilemap2.bin
echo | FE45_Compress.exe ../graphics/LVStatsCombat.bin
echo | FE45_Compress.exe ../graphics/LVStatsCombatTilemap.bin
echo | FE45_Compress.exe ../graphics/LvUpCombat.bin
echo | FE45_Compress.exe ../graphics/Options.bin
echo | FE45_Compress.exe ../graphics/TitleScreen.bin
echo | FE45_Compress.exe ../graphics/TradeBrownBars.bin
echo | FE45_Compress.exe ../graphics/WorldMap.dat
echo | FE45_Compress.exe ../graphics/WorldMapTilemap.dat

echo | FE45_Compress.exe ../graphics/intro_crawl/IntroPicture1.bin
echo | FE45_Compress.exe ../graphics/intro_crawl/IntroPicture2.bin
echo | FE45_Compress.exe ../graphics/intro_crawl/IntroPicture3.bin
echo | FE45_Compress.exe ../graphics/intro_crawl/IntroPicture4.bin
echo | FE45_Compress.exe ../graphics/intro_crawl/IntroPicture5.bin
echo | FE45_Compress.exe ../graphics/intro_crawl/IntroPicture6.bin
echo | FE45_Compress.exe ../graphics/intro_crawl/IntroText1.bin
echo | FE45_Compress.exe ../graphics/intro_crawl/IntroText2.bin
echo | FE45_Compress.exe ../graphics/intro_crawl/IntroTilemap1.bin
echo | FE45_Compress.exe ../graphics/intro_crawl/IntroTilemap2.bin
echo | FE45_Compress.exe ../graphics/intro_crawl/IntroTilemap3.bin
echo | FE45_Compress.exe ../graphics/intro_crawl/NintendoLogo.bin

echo | FE45_Compress.exe ../text_menus/tilemaps/InventoryTextTilemap1.bin
echo | FE45_Compress.exe ../text_menus/tilemaps/InventoryTextTilemap2.bin
echo | FE45_Compress.exe ../text_menus/tilemaps/ShopTilemap.bin
echo | FE45_Compress.exe ../text_menus/tilemaps/StatusScreenTilemap.bin
echo | FE45_Compress.exe ../text_menus/tilemaps/SupplyTilemap.bin