* = $354000
.logical $EAC000

	segmentStart

	aPortraitPalette00 .binary "sprites/PortraitPalette00.bin"
	aPortraitPalette01 .binary "sprites/PortraitPalette01.bin"
	aPortraitPalette02 .binary "sprites/PortraitPalette02.bin"
	aPortraitPalette03 .binary "sprites/PortraitPalette03.bin"
	aPortraitPalette04 .binary "sprites/PortraitPalette04.bin"
	aPortraitPalette05 .binary "sprites/PortraitPalette05.bin"
	aPortraitPalette06 .binary "sprites/PortraitPalette06.bin"
	aPortraitPalette07 .binary "sprites/PortraitPalette07.bin"
	aPortraitPalette08 .binary "sprites/PortraitPalette08.bin"
	aPortraitPalette09 .binary "sprites/PortraitPalette09.bin"
	aPortraitPalette0A .binary "sprites/PortraitPalette0A.bin"
	aPortraitPalette0B .binary "sprites/PortraitPalette0B.bin"
	aPortraitPalette0C .binary "sprites/PortraitPalette0C.bin"
	aPortraitPalette0D .binary "sprites/PortraitPalette0D.bin"
	aPortraitPalette0E .binary "sprites/PortraitPalette0E.bin"
	aPortraitPalette0F .binary "sprites/PortraitPalette0F.bin"
	aPortraitPalette10 .binary "sprites/PortraitPalette10.bin"
	aPortraitPalette11 .binary "sprites/PortraitPalette11.bin"
	aPortraitPalette12 .binary "sprites/PortraitPalette12.bin"
	aPortraitPalette13 .binary "sprites/PortraitPalette13.bin"
	aPortraitPalette14 .binary "sprites/PortraitPalette14.bin"
	aPortraitPalette15 .binary "sprites/PortraitPalette15.bin"
	aPortraitPalette16 .binary "sprites/PortraitPalette16.bin"
	aPortraitPalette17 .binary "sprites/PortraitPalette17.bin"
	aPortraitPalette18 .binary "sprites/PortraitPalette18.bin"
	aPortraitPalette19 .binary "sprites/PortraitPalette19.bin"
	aPortraitPalette1A .binary "sprites/PortraitPalette1A.bin"
	aPortraitPalette1B .binary "sprites/PortraitPalette1B.bin"
	aPortraitPalette1C .binary "sprites/PortraitPalette1C.bin"
	aPortraitPalette1D .binary "sprites/PortraitPalette1D.bin"
	aPortraitPalette1E .binary "sprites/PortraitPalette1E.bin"
	aPortraitPalette1F .binary "sprites/PortraitPalette1F.bin"
	aPortraitPalette20 .binary "sprites/PortraitPalette20.bin"
	aPortraitPalette21 .binary "sprites/PortraitPalette21.bin"
	aPortraitPalette22 .binary "sprites/PortraitPalette22.bin"
	aPortraitPalette23 .binary "sprites/PortraitPalette23.bin"
	aPortraitPalette24 .binary "sprites/PortraitPalette24.bin"
	aPortraitPalette25 .binary "sprites/PortraitPalette25.bin"
	aPortraitPalette26 .binary "sprites/PortraitPalette26.bin"
	aPortraitPalette27 .binary "sprites/PortraitPalette27.bin"
	aPortraitPalette28 .binary "sprites/PortraitPalette28.bin"
	aPortraitPalette29 .binary "sprites/PortraitPalette29.bin"
	aPortraitPalette2A .binary "sprites/PortraitPalette2A.bin"
	aPortraitPalette2B .binary "sprites/PortraitPalette2B.bin"
	aPortraitPalette2C .binary "sprites/PortraitPalette2C.bin"
	aPortraitPalette2D .binary "sprites/PortraitPalette2D.bin"
	aPortraitPalette2E .binary "sprites/PortraitPalette2E.bin"
	aPortraitPalette2F .binary "sprites/PortraitPalette2F.bin"
	aPortraitPalette30 .binary "sprites/PortraitPalette30.bin"
	aPortraitPalette31 .binary "sprites/PortraitPalette31.bin"
	aPortraitPalette32 .binary "sprites/PortraitPalette32.bin"
	aPortraitPalette33 .binary "sprites/PortraitPalette33.bin"
	aPortraitPalette34 .binary "sprites/PortraitPalette34.bin"
	aPortraitPalette35 .binary "sprites/PortraitPalette35.bin"
	aPortraitPalette36 .binary "sprites/PortraitPalette36.bin"
	aPortraitPalette37 .binary "sprites/PortraitPalette37.bin"
	aPortraitPalette38 .binary "sprites/PortraitPalette38.bin"
	aPortraitPalette39 .binary "sprites/PortraitPalette39.bin"
	aPortraitPalette3A .binary "sprites/PortraitPalette3A.bin"
	aPortraitPalette3B .binary "sprites/PortraitPalette3B.bin"
	aPortraitPalette3C .binary "sprites/PortraitPalette3C.bin"
	aPortraitPalette3D .binary "sprites/PortraitPalette3D.bin"
	aPortraitPalette3E .binary "sprites/PortraitPalette3E.bin"
	aPortraitPalette3F .binary "sprites/PortraitPalette3F.bin"
	aPortraitPalette40 .binary "sprites/PortraitPalette40.bin"
	aPortraitPalette41 .binary "sprites/PortraitPalette41.bin"
	aPortraitPalette42 .binary "sprites/PortraitPalette42.bin"
	aPortraitPalette43 .binary "sprites/PortraitPalette43.bin"
	aPortraitPalette44 .binary "sprites/PortraitPalette44.bin"
	aPortraitPalette45 .binary "sprites/PortraitPalette45.bin"
	aPortraitPalette46 .binary "sprites/PortraitPalette46.bin"
	aPortraitPalette47 .binary "sprites/PortraitPalette47.bin"
	aPortraitPalette48 .binary "sprites/PortraitPalette48.bin"
	aPortraitPalette49 .binary "sprites/PortraitPalette49.bin"
	aPortraitPalette4A .binary "sprites/PortraitPalette4A.bin"
	aPortraitPalette4B .binary "sprites/PortraitPalette4B.bin"
	aPortraitPalette4C .binary "sprites/PortraitPalette4C.bin"
	aPortraitPalette4D .binary "sprites/PortraitPalette4D.bin"
	aPortraitPalette4E .binary "sprites/PortraitPalette4E.bin"
	aPortraitPalette4F .binary "sprites/PortraitPalette4F.bin"
	aPortraitPalette50 .binary "sprites/PortraitPalette50.bin"
	aPortraitPalette51 .binary "sprites/PortraitPalette51.bin"
	aPortraitPalette52 .binary "sprites/PortraitPalette52.bin"
	aPortraitPalette53 .binary "sprites/PortraitPalette53.bin"
	aPortraitPalette54 .binary "sprites/PortraitPalette54.bin"
	aPortraitPalette55 .binary "sprites/PortraitPalette55.bin"
	aPortraitPalette56 .binary "sprites/PortraitPalette56.bin"
	aPortraitPalette57 .binary "sprites/PortraitPalette57.bin"
	aPortraitPalette58 .binary "sprites/PortraitPalette58.bin"
	aPortraitPalette59 .binary "sprites/PortraitPalette59.bin"
	aPortraitPalette5A .binary "sprites/PortraitPalette5A.bin"
	aPortraitPalette5B .binary "sprites/PortraitPalette5B.bin"
	aPortraitPalette5C .binary "sprites/PortraitPalette5C.bin"
	aPortraitPalette5D .binary "sprites/PortraitPalette5D.bin"
	aPortraitPalette5E .binary "sprites/PortraitPalette5E.bin"
	aPortraitPalette5F .binary "sprites/PortraitPalette5F.bin"
	aPortraitPalette60 .binary "sprites/PortraitPalette60.bin"
	aPortraitPalette61 .binary "sprites/PortraitPalette61.bin"
	aPortraitPalette62 .binary "sprites/PortraitPalette62.bin"
	aPortraitPalette63 .binary "sprites/PortraitPalette63.bin"
	aPortraitPalette64 .binary "sprites/PortraitPalette64.bin"
	aPortraitPalette65 .binary "sprites/PortraitPalette65.bin"
	aPortraitPalette66 .binary "sprites/PortraitPalette66.bin"
	aPortraitPalette67 .binary "sprites/PortraitPalette67.bin"
	aPortraitPalette68 .binary "sprites/PortraitPalette68.bin"
	aPortraitPalette69 .binary "sprites/PortraitPalette69.bin"
	aPortraitPalette6A .binary "sprites/PortraitPalette6A.bin"
	aPortraitPalette6B .binary "sprites/PortraitPalette6B.bin"
	aPortraitPalette6C .binary "sprites/PortraitPalette6C.bin"
	aPortraitPalette6D .binary "sprites/PortraitPalette6D.bin"
	aPortraitPalette6E .binary "sprites/PortraitPalette6E.bin"
	aPortraitPalette6F .binary "sprites/PortraitPalette6F.bin"
	aPortraitPalette70 .binary "sprites/PortraitPalette70.bin"
	aPortraitPalette71 .binary "sprites/PortraitPalette71.bin"
	aPortraitPalette72 .binary "sprites/PortraitPalette72.bin"
	aPortraitPalette73 .binary "sprites/PortraitPalette73.bin"
	aPortraitPalette74 .binary "sprites/PortraitPalette74.bin"
	aPortraitPalette75 .binary "sprites/PortraitPalette75.bin"
	aPortraitPalette76 .binary "sprites/PortraitPalette76.bin"
	aPortraitPalette77 .binary "sprites/PortraitPalette77.bin"
	aPortraitPalette78 .binary "sprites/PortraitPalette78.bin"
	aPortraitPalette79 .binary "sprites/PortraitPalette79.bin"
	aPortraitPalette7A .binary "sprites/PortraitPalette7A.bin"
	aPortraitPalette7B .binary "sprites/PortraitPalette7B.bin"
	aPortraitPalette7C .binary "sprites/PortraitPalette7C.bin"
	aPortraitPalette7D .binary "sprites/PortraitPalette7D.bin"
	aPortraitPalette7E .binary "sprites/PortraitPalette7E.bin"
	aPortraitPalette7F .binary "sprites/PortraitPalette7F.bin"
	aPortraitPalette80 .binary "sprites/PortraitPalette80.bin"
	aPortraitPalette81 .binary "sprites/PortraitPalette81.bin"
	aPortraitPalette82 .binary "sprites/PortraitPalette82.bin"
	aPortraitPalette83 .binary "sprites/PortraitPalette83.bin"
	aPortraitPalette84 .binary "sprites/PortraitPalette84.bin"
	aPortraitPalette85 .binary "sprites/PortraitPalette85.bin"
	aPortraitPalette86 .binary "sprites/PortraitPalette86.bin"
	aPortraitPalette87 .binary "sprites/PortraitPalette87.bin"
	aPortraitPalette88 .binary "sprites/PortraitPalette88.bin"
	aPortraitPalette89 .binary "sprites/PortraitPalette89.bin"
	aPortraitPalette8A .binary "sprites/PortraitPalette8A.bin"
	aPortraitPalette8B .binary "sprites/PortraitPalette8B.bin"
	aPortraitPalette8C .binary "sprites/PortraitPalette8C.bin"
	aPortraitPalette8D .binary "sprites/PortraitPalette8D.bin"
	aPortraitPalette8E .binary "sprites/PortraitPalette8E.bin"
	aPortraitPalette8F .binary "sprites/PortraitPalette8F.bin"
	aPortraitPalette90 .binary "sprites/PortraitPalette90.bin"
	aPortraitPalette91 .binary "sprites/PortraitPalette91.bin"
	aPortraitPalette92 .binary "sprites/PortraitPalette92.bin"
	aPortraitPalette93 .binary "sprites/PortraitPalette93.bin"
	aPortraitPalette94 .binary "sprites/PortraitPalette94.bin"
	aPortraitPalette95 .binary "sprites/PortraitPalette95.bin"
	aPortraitPalette96 .binary "sprites/PortraitPalette96.bin"
	aPortraitPalette97 .binary "sprites/PortraitPalette97.bin"
	aPortraitPalette98 .binary "sprites/PortraitPalette98.bin"
	aPortraitPalette99 .binary "sprites/PortraitPalette99.bin"
	aPortraitPalette9A .binary "sprites/PortraitPalette9A.bin"
	aPortraitPalette9B .binary "sprites/PortraitPalette9B.bin"
	aPortraitPalette9C .binary "sprites/PortraitPalette9C.bin"
	aPortraitPalette9D .binary "sprites/PortraitPalette9D.bin"
	aPortraitPalette9E .binary "sprites/PortraitPalette9E.bin"
	aPortraitPalette9F .binary "sprites/PortraitPalette9F.bin"
	aPortraitPaletteA0 .binary "sprites/PortraitPaletteA0.bin"
	aPortraitPaletteA1 .binary "sprites/PortraitPaletteA1.bin"
	aPortraitPaletteA2 .binary "sprites/PortraitPaletteA2.bin"
	aPortraitPaletteA3 .binary "sprites/PortraitPaletteA3.bin"
	aPortraitPaletteA4 .binary "sprites/PortraitPaletteA4.bin"
	aPortraitPaletteA5 .binary "sprites/PortraitPaletteA5.bin"
	aPortraitPaletteA6 .binary "sprites/PortraitPaletteA6.bin"
	aPortraitPaletteA7 .binary "sprites/PortraitPaletteA7.bin"
	aPortraitPaletteA8 .binary "sprites/PortraitPaletteA8.bin"
	aPortraitPaletteA9 .binary "sprites/PortraitPaletteA9.bin"
	aPortraitPaletteAA .binary "sprites/PortraitPaletteAA.bin"
	aPortraitPaletteAB .binary "sprites/PortraitPaletteAB.bin"
	aPortraitPaletteAC .binary "sprites/PortraitPaletteAC.bin"
	aPortraitPaletteAD .binary "sprites/PortraitPaletteAD.bin"
	aPortraitPaletteAE .binary "sprites/PortraitPaletteAE.bin"
	aPortraitPaletteAF .binary "sprites/PortraitPaletteAF.bin"
	aPortraitPaletteB0 .binary "sprites/PortraitPaletteB0.bin"
	aPortraitPaletteB1 .binary "sprites/PortraitPaletteB1.bin"
	aPortraitPaletteB2 .binary "sprites/PortraitPaletteB2.bin"
	aPortraitPaletteB3 .binary "sprites/PortraitPaletteB3.bin"
	aPortraitPaletteB4 .binary "sprites/PortraitPaletteB4.bin"
	aPortraitPaletteB5 .binary "sprites/PortraitPaletteB5.bin"
	aPortraitPaletteB6 .binary "sprites/PortraitPaletteB6.bin"
	aPortraitPaletteB7 .binary "sprites/PortraitPaletteB7.bin"
	aPortraitPaletteB8 .binary "sprites/PortraitPaletteB8.bin"
	aPortraitPaletteB9 .binary "sprites/PortraitPaletteB9.bin"
	aPortraitPaletteBA .binary "sprites/PortraitPaletteBA.bin"
	aPortraitPaletteBB .binary "sprites/PortraitPaletteBB.bin"
	aPortraitPaletteBC .binary "sprites/PortraitPaletteBC.bin"
	aPortraitPaletteBD .binary "sprites/PortraitPaletteBD.bin"
	aPortraitPaletteBE .binary "sprites/PortraitPaletteBE.bin"
	aPortraitPaletteBF .binary "sprites/PortraitPaletteBF.bin"
	aPortraitPaletteC0 .binary "sprites/PortraitPaletteC0.bin"
	aPortraitPaletteC1 .binary "sprites/PortraitPaletteC1.bin"
	aPortraitPaletteC2 .binary "sprites/PortraitPaletteC2.bin"
	aPortraitPaletteC3 .binary "sprites/PortraitPaletteC3.bin"
	aPortraitPaletteC4 .binary "sprites/PortraitPaletteC4.bin"
	aPortraitPaletteC5 .binary "sprites/PortraitPaletteC5.bin"
	aPortraitPaletteC6 .binary "sprites/PortraitPaletteC6.bin"
	aPortraitPaletteC7 .binary "sprites/PortraitPaletteC7.bin"
	aPortraitPaletteC8 .binary "sprites/PortraitPaletteC8.bin"
	aPortraitPaletteC9 .binary "sprites/PortraitPaletteC9.bin"
	aPortraitPaletteCA .binary "sprites/PortraitPaletteCA.bin"
	aPortraitPaletteCB .binary "sprites/PortraitPaletteCB.bin"
	aPortraitPaletteCC .binary "sprites/PortraitPaletteCC.bin"
	aPortraitPaletteCD .binary "sprites/PortraitPaletteCD.bin"
	aPortraitPaletteCE .binary "sprites/PortraitPaletteCE.bin"
	aPortraitPaletteCF .binary "sprites/PortraitPaletteCF.bin"
	aPortraitPaletteD0 .binary "sprites/PortraitPaletteD0.bin"
	aPortraitPaletteD1 .binary "sprites/PortraitPaletteD1.bin"
	aPortraitPaletteD2 .binary "sprites/PortraitPaletteD2.bin"
	aPortraitPaletteD3 .binary "sprites/PortraitPaletteD3.bin"
	aPortraitPaletteD4 .binary "sprites/PortraitPaletteD4.bin"
	aPortraitPaletteD5 .binary "sprites/PortraitPaletteD5.bin"
	aPortraitPaletteD6 .binary "sprites/PortraitPaletteD6.bin"
	aPortraitPaletteD7 .binary "sprites/PortraitPaletteD7.bin"
	aPortraitPaletteD8 .binary "sprites/PortraitPaletteD8.bin"
	aPortraitPaletteD9 .binary "sprites/PortraitPaletteD9.bin"
	aPortraitPaletteDA .binary "sprites/PortraitPaletteDA.bin"
	aPortraitPaletteDB .binary "sprites/PortraitPaletteDB.bin"
	aPortraitPaletteDC .binary "sprites/PortraitPaletteDC.bin"
	aPortraitPaletteDD .binary "sprites/PortraitPaletteDD.bin"
	aPortraitPaletteDE .binary "sprites/PortraitPaletteDE.bin"
	aPortraitPaletteDF .binary "sprites/PortraitPaletteDF.bin"
	aPortraitPaletteE0 .binary "sprites/PortraitPaletteE0.bin"
	aPortraitPaletteE1 .binary "sprites/PortraitPaletteE1.bin"
	aPortraitPaletteE2 .binary "sprites/PortraitPaletteE2.bin"
	aPortraitPaletteE3 .binary "sprites/PortraitPaletteE3.bin"
	aPortraitPaletteE4 .binary "sprites/PortraitPaletteE4.bin"
	aPortraitPaletteE5 .binary "sprites/PortraitPaletteE5.bin"
	aPortraitPaletteE6 .binary "sprites/PortraitPaletteE6.bin"
	aPortraitPaletteE7 .binary "sprites/PortraitPaletteE7.bin"
	aPortraitPaletteE8 .binary "sprites/PortraitPaletteE8.bin"
	aPortraitPaletteE9 .binary "sprites/PortraitPaletteE9.bin"
	aPortraitPaletteEA .binary "sprites/PortraitPaletteEA.bin"
	aPortraitPaletteEB .binary "sprites/PortraitPaletteEB.bin"
	aPortraitPaletteEC .binary "sprites/PortraitPaletteEC.bin"
	aPortraitPaletteED .binary "sprites/PortraitPaletteED.bin"
	aPortraitPaletteEE .binary "sprites/PortraitPaletteEE.bin"
	aPortraitPaletteEF .binary "sprites/PortraitPaletteEF.bin"
	aPortraitPaletteF0 .binary "sprites/PortraitPaletteF0.bin"
	aPortraitPaletteF1 .binary "sprites/PortraitPaletteF1.bin"
	aPortraitPaletteF2 .binary "sprites/PortraitPaletteF2.bin"
	aPortraitPaletteF3 .binary "sprites/PortraitPaletteF3.bin"

	g4bppcPortraitEADE80 .binary "sprites/PortraitEADE80.4bpp.comp"
	g4bppcPortraitEAE3B9 .binary "sprites/PortraitEAE3B9.4bpp.comp"
	g4bppcPortraitEAE8B7 .binary "sprites/PortraitEAE8B7.4bpp.comp"
	g4bppcPortraitEAEE23 .binary "sprites/PortraitEAEE23.4bpp.comp"
	g4bppcPortraitEAF322 .binary "sprites/PortraitEAF322.4bpp.comp"
	g4bppcPortraitEAF8A6 .binary "sprites/PortraitEAF8A6.4bpp.comp"
	g4bppcPortraitEAFE34 .binary "sprites/PortraitEAFE34.4bpp.comp"

	segmentEnd $EB0318

.here

* = $358318
.logical $EB8318

	segmentStart

	g4bppcPortraitEB8318 .binary "sprites/PortraitEB8318.4bpp.comp"
	g4bppcPortraitEB8851 .binary "sprites/PortraitEB8851.4bpp.comp"
	g4bppcPortraitEB8C84 .binary "sprites/PortraitEB8C84.4bpp.comp"
	g4bppcPortraitEB91DE .binary "sprites/PortraitEB91DE.4bpp.comp"
	g4bppcPortraitEB9717 .binary "sprites/PortraitEB9717.4bpp.comp"
	g4bppcPortraitEB9BD9 .binary "sprites/PortraitEB9BD9.4bpp.comp"
	g4bppcPortraitEBA119 .binary "sprites/PortraitEBA119.4bpp.comp"
	g4bppcPortraitEBA613 .binary "sprites/PortraitEBA613.4bpp.comp"
	g4bppcPortraitEBAB36 .binary "sprites/PortraitEBAB36.4bpp.comp"
	g4bppcPortraitEBB048 .binary "sprites/PortraitEBB048.4bpp.comp"
	g4bppcPortraitEBB605 .binary "sprites/PortraitEBB605.4bpp.comp"
	g4bppcPortraitEBBADC .binary "sprites/PortraitEBBADC.4bpp.comp"
	g4bppcPortraitEBBFB5 .binary "sprites/PortraitEBBFB5.4bpp.comp"
	g4bppcPortraitEBC4CE .binary "sprites/PortraitEBC4CE.4bpp.comp"
	g4bppcPortraitEBC9DC .binary "sprites/PortraitEBC9DC.4bpp.comp"
	g4bppcPortraitEBCF30 .binary "sprites/PortraitEBCF30.4bpp.comp"
	g4bppcPortraitEBD3D2 .binary "sprites/PortraitEBD3D2.4bpp.comp"
	g4bppcPortraitEBD981 .binary "sprites/PortraitEBD981.4bpp.comp"
	g4bppcPortraitEBDE20 .binary "sprites/PortraitEBDE20.4bpp.comp"
	g4bppcPortraitEBE3F9 .binary "sprites/PortraitEBE3F9.4bpp.comp"
	g4bppcPortraitEBE928 .binary "sprites/PortraitEBE928.4bpp.comp"
	g4bppcPortraitEBEE1D .binary "sprites/PortraitEBEE1D.4bpp.comp"
	g4bppcPortraitEBF2FF .binary "sprites/PortraitEBF2FF.4bpp.comp"
	g4bppcPortraitEBF862 .binary "sprites/PortraitEBF862.4bpp.comp"
	g4bppcPortraitEBFD2F .binary "sprites/PortraitEBFD2F.4bpp.comp"

	segmentEnd $EC0209

.here

* = $360209
.logical $EC8209

	segmentStart

	g4bppcPortraitEC8209 .binary "sprites/PortraitEC8209.4bpp.comp"
	g4bppcPortraitEC8729 .binary "sprites/PortraitEC8729.4bpp.comp"
	g4bppcPortraitEC8C0D .binary "sprites/PortraitEC8C0D.4bpp.comp"
	g4bppcPortraitEC9117 .binary "sprites/PortraitEC9117.4bpp.comp"
	g4bppcPortraitEC95D7 .binary "sprites/PortraitEC95D7.4bpp.comp"
	g4bppcPortraitEC9AB8 .binary "sprites/PortraitEC9AB8.4bpp.comp"
	g4bppcPortraitEC9F78 .binary "sprites/PortraitEC9F78.4bpp.comp"
	g4bppcPortraitECA4EE .binary "sprites/PortraitECA4EE.4bpp.comp"
	g4bppcPortraitECAA94 .binary "sprites/PortraitECAA94.4bpp.comp"
	g4bppcPortraitECAFB9 .binary "sprites/PortraitECAFB9.4bpp.comp"
	g4bppcPortraitECB499 .binary "sprites/PortraitECB499.4bpp.comp"
	g4bppcPortraitECB9C0 .binary "sprites/PortraitECB9C0.4bpp.comp"
	g4bppcPortraitECBE8D .binary "sprites/PortraitECBE8D.4bpp.comp"
	g4bppcPortraitECC30D .binary "sprites/PortraitECC30D.4bpp.comp"
	g4bppcPortraitECC815 .binary "sprites/PortraitECC815.4bpp.comp"
	g4bppcPortraitECCCDA .binary "sprites/PortraitECCCDA.4bpp.comp"
	g4bppcPortraitECD24C .binary "sprites/PortraitECD24C.4bpp.comp"
	g4bppcPortraitECD78C .binary "sprites/PortraitECD78C.4bpp.comp"
	g4bppcPortraitECDC66 .binary "sprites/PortraitECDC66.4bpp.comp"
	g4bppcPortraitECE173 .binary "sprites/PortraitECE173.4bpp.comp"
	g4bppcPortraitECE62B .binary "sprites/PortraitECE62B.4bpp.comp"
	g4bppcPortraitECEB79 .binary "sprites/PortraitECEB79.4bpp.comp"
	g4bppcPortraitECF0A4 .binary "sprites/PortraitECF0A4.4bpp.comp"
	g4bppcPortraitECF4EA .binary "sprites/PortraitECF4EA.4bpp.comp"
	g4bppcPortraitECF9CB .binary "sprites/PortraitECF9CB.4bpp.comp"
	g4bppcPortraitECFE67 .binary "sprites/PortraitECFE67.4bpp.comp"

	segmentEnd $ED0356

.here

* = $368356
.logical $ED8356

	segmentStart

	g4bppcPortraitED8356 .binary "sprites/PortraitED8356.4bpp.comp"
	g4bppcPortraitED885F .binary "sprites/PortraitED885F.4bpp.comp"
	g4bppcPortraitED8DD2 .binary "sprites/PortraitED8DD2.4bpp.comp"
	g4bppcPortraitED930E .binary "sprites/PortraitED930E.4bpp.comp"
	g4bppcPortraitED9854 .binary "sprites/PortraitED9854.4bpp.comp"
	g4bppcPortraitED9D9B .binary "sprites/PortraitED9D9B.4bpp.comp"
	g4bppcPortraitEDA2CB .binary "sprites/PortraitEDA2CB.4bpp.comp"
	g4bppcPortraitEDA84E .binary "sprites/PortraitEDA84E.4bpp.comp"
	g4bppcPortraitEDAD56 .binary "sprites/PortraitEDAD56.4bpp.comp"
	g4bppcPortraitEDB266 .binary "sprites/PortraitEDB266.4bpp.comp"
	g4bppcPortraitEDB735 .binary "sprites/PortraitEDB735.4bpp.comp"
	g4bppcPortraitEDBBDE .binary "sprites/PortraitEDBBDE.4bpp.comp"
	g4bppcPortraitEDC098 .binary "sprites/PortraitEDC098.4bpp.comp"
	g4bppcPortraitEDC56B .binary "sprites/PortraitEDC56B.4bpp.comp"
	g4bppcPortraitEDC9FC .binary "sprites/PortraitEDC9FC.4bpp.comp"
	g4bppcPortraitEDCEA0 .binary "sprites/PortraitEDCEA0.4bpp.comp"
	g4bppcPortraitEDD314 .binary "sprites/PortraitEDD314.4bpp.comp"
	g4bppcPortraitEDD7B0 .binary "sprites/PortraitEDD7B0.4bpp.comp"
	g4bppcPortraitEDDC05 .binary "sprites/PortraitEDDC05.4bpp.comp"
	g4bppcPortraitEDE09F .binary "sprites/PortraitEDE09F.4bpp.comp"
	g4bppcPortraitEDE4DA .binary "sprites/PortraitEDE4DA.4bpp.comp"
	g4bppcPortraitEDE988 .binary "sprites/PortraitEDE988.4bpp.comp"
	g4bppcPortraitEDED87 .binary "sprites/PortraitEDED87.4bpp.comp"
	g4bppcPortraitEDF246 .binary "sprites/PortraitEDF246.4bpp.comp"
	g4bppcPortraitEDF6BA .binary "sprites/PortraitEDF6BA.4bpp.comp"
	g4bppcPortraitEDFBE9 .binary "sprites/PortraitEDFBE9.4bpp.comp"

	segmentEnd $EE0071

.here

* = $370071
.logical $EE8071

	segmentStart

	g4bppcPortraitEE8071 .binary "sprites/PortraitEE8071.4bpp.comp"
	g4bppcPortraitEE84E4 .binary "sprites/PortraitEE84E4.4bpp.comp"
	g4bppcPortraitEE89F5 .binary "sprites/PortraitEE89F5.4bpp.comp"
	g4bppcPortraitEE8ED4 .binary "sprites/PortraitEE8ED4.4bpp.comp"
	g4bppcPortraitEE9378 .binary "sprites/PortraitEE9378.4bpp.comp"
	g4bppcPortraitEE9840 .binary "sprites/PortraitEE9840.4bpp.comp"
	g4bppcPortraitEE9D0E .binary "sprites/PortraitEE9D0E.4bpp.comp"
	g4bppcPortraitEEA236 .binary "sprites/PortraitEEA236.4bpp.comp"
	g4bppcPortraitEEA74E .binary "sprites/PortraitEEA74E.4bpp.comp"
	g4bppcPortraitEEAC11 .binary "sprites/PortraitEEAC11.4bpp.comp"
	g4bppcPortraitEEB0AB .binary "sprites/PortraitEEB0AB.4bpp.comp"
	g4bppcPortraitEEB5B3 .binary "sprites/PortraitEEB5B3.4bpp.comp"
	g4bppcPortraitEEBA8A .binary "sprites/PortraitEEBA8A.4bpp.comp"
	g4bppcPortraitEEBF63 .binary "sprites/PortraitEEBF63.4bpp.comp"
	g4bppcPortraitEEC477 .binary "sprites/PortraitEEC477.4bpp.comp"
	g4bppcPortraitEEC97A .binary "sprites/PortraitEEC97A.4bpp.comp"
	g4bppcPortraitEECDC7 .binary "sprites/PortraitEECDC7.4bpp.comp"
	g4bppcPortraitEED20C .binary "sprites/PortraitEED20C.4bpp.comp"
	g4bppcPortraitEED6A3 .binary "sprites/PortraitEED6A3.4bpp.comp"
	g4bppcPortraitEEDB4B .binary "sprites/PortraitEEDB4B.4bpp.comp"
	g4bppcPortraitEEE104 .binary "sprites/PortraitEEE104.4bpp.comp"
	g4bppcPortraitEEE595 .binary "sprites/PortraitEEE595.4bpp.comp"
	g4bppcPortraitEEE986 .binary "sprites/PortraitEEE986.4bpp.comp"
	g4bppcPortraitEEEE9B .binary "sprites/PortraitEEEE9B.4bpp.comp"
	g4bppcPortraitEEF32A .binary "sprites/PortraitEEF32A.4bpp.comp"
	g4bppcPortraitEEF712 .binary "sprites/PortraitEEF712.4bpp.comp"
	g4bppcPortraitEEFC0A .binary "sprites/PortraitEEFC0A.4bpp.comp"

	segmentEnd $EF0019

.here

* = $378019
.logical $EF8019

	segmentStart

	g4bppcPortraitEF8019 .binary "sprites/PortraitEF8019.4bpp.comp"
	g4bppcPortraitEF8470 .binary "sprites/PortraitEF8470.4bpp.comp"
	g4bppcPortraitEF88E7 .binary "sprites/PortraitEF88E7.4bpp.comp"
	g4bppcPortraitEF8D9C .binary "sprites/PortraitEF8D9C.4bpp.comp"
	g4bppcPortraitEF91AA .binary "sprites/PortraitEF91AA.4bpp.comp"
	g4bppcPortraitEF95C0 .binary "sprites/PortraitEF95C0.4bpp.comp"
	g4bppcPortraitEF99BC .binary "sprites/PortraitEF99BC.4bpp.comp"
	g4bppcPortraitEF9DCD .binary "sprites/PortraitEF9DCD.4bpp.comp"
	g4bppcPortraitEFA1F5 .binary "sprites/PortraitEFA1F5.4bpp.comp"
	g4bppcPortraitEFA64C .binary "sprites/PortraitEFA64C.4bpp.comp"
	g4bppcPortraitEFAA5D .binary "sprites/PortraitEFAA5D.4bpp.comp"
	g4bppcPortraitEFAEBF .binary "sprites/PortraitEFAEBF.4bpp.comp"
	g4bppcPortraitEFB317 .binary "sprites/PortraitEFB317.4bpp.comp"
	g4bppcPortraitEFB75D .binary "sprites/PortraitEFB75D.4bpp.comp"
	g4bppcPortraitEFBB1D .binary "sprites/PortraitEFBB1D.4bpp.comp"
	g4bppcPortraitEFBF16 .binary "sprites/PortraitEFBF16.4bpp.comp"
	g4bppcPortraitEFC3DD .binary "sprites/PortraitEFC3DD.4bpp.comp"
	g4bppcPortraitEFC7D1 .binary "sprites/PortraitEFC7D1.4bpp.comp"
	g4bppcPortraitEFCB8F .binary "sprites/PortraitEFCB8F.4bpp.comp"
	g4bppcPortraitEFCFD4 .binary "sprites/PortraitEFCFD4.4bpp.comp"
	g4bppcPortraitEFD3A1 .binary "sprites/PortraitEFD3A1.4bpp.comp"
	g4bppcPortraitEFD772 .binary "sprites/PortraitEFD772.4bpp.comp"
	g4bppcPortraitEFDC2E .binary "sprites/PortraitEFDC2E.4bpp.comp"
	g4bppcPortraitEFE053 .binary "sprites/PortraitEFE053.4bpp.comp"
	g4bppcPortraitEFE47D .binary "sprites/PortraitEFE47D.4bpp.comp"
	g4bppcPortraitEFE801 .binary "sprites/PortraitEFE801.4bpp.comp"
	g4bppcPortraitEFEBDE .binary "sprites/PortraitEFEBDE.4bpp.comp"
	g4bppcPortraitEFEF61 .binary "sprites/PortraitEFEF61.4bpp.comp"

	segmentEnd

.here