

	TypeSword   = 00
	TypeLance   = 01
	TypeAxe     = 02
	TypeBow     = 03
	TypeStaff   = 04
	TypeFire    = 05
	TypeThunder = 06
	TypeWind    = 07
	TypeLight   = 08
	TypeDark    = 09

	TypeItem    = 11

	WeaponRankIncrement = 50

	RankE = WeaponRankIncrement * 1
	RankD = WeaponRankIncrement * 2
	RankC = WeaponRankIncrement * 3
	RankB = WeaponRankIncrement * 4
	RankA = WeaponRankIncrement * 5

	TraitBallista     = %00000001 ; $01
	TraitMagicRanged  = %00000010 ; $02
	TraitWeapon       = %00000100 ; $04
	TraitTome         = %00001000 ; $08
	TraitStaff        = %00010000 ; $10
	TraitUnbreakable  = %00100000 ; $20
	TraitUnsellable   = %01000000 ; $40
	TraitBroken       = %10000000 ; $80
	
	PoisonEffect	  = 1*2
	CurseEffect		  = 2*2
	DrainEffect		  = 3*2
	StoneEffect		  = 4*2
	HelEffect		  = 5*2
	BerserkEffect	  = 6*2
	SleepEffect		  = 7*2
	
	LuckRingUse       = 1*2
	LifeRingUse       = 2*2
	SpeedRingUse      = 3*2
	MagicRingUse      = 4*2
	StrengthRingUse   = 5*2
	BodyRingUse       = 6*2
	ShieldRingUse     = 7*2
	SkillRingUse      = 8*2
	LegRingUse        = 9*2
	
	MasterSealUse     = 10*2
	MasterCrownUse    = 11*2
	ChestKeyUse       = 12*2
	DoorKeyUse        = 13*2
	BridgeKeyUse      = 14*2
	LockpickUse       = 15*2
	VulneraryUse	  = 16*2
	PureWaterUse      = 17*2
	TorchUse          = 18*2
	AntitoxinUse      = 19*2
	
	ParagonManualUse  = 20*2
	AccostManualUse   = 21*2
	BargainManualUse  = 22*2
	VantageManualUse  = 23*2
	WrathManualUse    = 24*2
	AdeptManualUse    = 25*2
	MiracleManualUse  = 26*2
	NihilManualUse    = 27*2
	SolManualUse      = 28*2
	LunaManualUse     = 29*2
	
	HealUse           = 30*2
	MendUse           = 31*2
	RecoverUse        = 32*2
	PhysicUse         = 33*2
	FortifyUse        = 34*2
	RescueUse         = 35*2
	WarpUse           = 36*2
	RestoreUse        = 37*2
	SilenceUse        = 38*2
	SleepUse          = 39*2
	TorchStaffUse     = 40*2
	ReturnStaffUse    = 41*2
	HammerneUse       = 42*2
	ThiefStaffUse     = 43*2
	WatchUse          = 44*2
	BerserkUse        = 45*2
	UnlockUse         = 46*2
	EnsorcelUse       = 47*2
	RewarpUse         = 48*2
	
	StaminaDrinkUse   = 51*2
	KiaUse			  = 52*2
	
	