	MS_SoundInfantry     = 1
    MS_SoundArmor        = 2
    MS_SoundMountedTier1 = 3
    MS_SoundMountedTier2 = 4
    MS_SoundFlying       = 5


;	Map weapon graphics

	aMapAnim_None						= $A0DCE0

	aMapAnim_Swords						= $A0ABE0
	aMapAnim_IronBlade					= $A0ACE0
	aMapAnim_LandsSword					= $A0ADE0
	aMapAnim_BragisBlade_Kingmaker		= $A0AEE0
	aMapAnim_UnusedSword1				= $A0AFE0
	aMapAnim_UnusedSword2				= $A0B0E0
	aMapAnim_KillingEdge_LightningSword	= $A0B1E0
	aMapAnim_Blessed_ParagonSword_LightBrand	= $A0B2E0
	aMapAnim_WindSword					= $A0B3E0
	aMapAnim_FlameSword					= $A0B4E0
	aMapAnim_BigSwords					= $A0B5E0
	aMapAnim_Rapier						= $A0B6E0
	aMapAnim_Armorslayer				= $A0B7E0
	aMapAnim_BraveSword					= $A0B8E0
	aMapAnim_VeninEdge_Shortsword		= $A0B9E0
	aMapAnim_Longsword					= $A0BAE0
	aMapAnim_Greatsword					= $A0BBE0
	aMapAnim_MasterSword				= $A0BCE0
	aMapAnim_ShadowSword				= $A0BDE0
	aMapAnim_Lances						= $A0BEE0
	aMapAnim_UnusedLance1				= $A0BFE0
	aMapAnim_Javelin					= $A0C0E0
	aMapAnim_ShadowSpear				= $A0C1E0
	aMapAnim_Ridersbane					= $A0C2E0
	aMapAnim_BraveLance					= $A0C3E0
	aMapAnim_Slim_KillerLance			= $A0C4E0
	aMapAnim_UnusedLance2				= $A0C5E0
	aMapAnim_Venin_ShortLance			= $A0C6E0
	aMapAnim_LongLance					= $A0C7E0
	aMapAnim_GreatLance					= $A0C8E0
	aMapAnim_MasterLance				= $A0C9E0
	aMapAnim_Dragonpike					= $A0CAE0
	aMapAnim_GaeBolg_Gungnir			= $A0CBE0
	aMapAnim_Axes						= $A0CCE0
	aMapAnim_Hammer						= $A0CDE0
	aMapAnim_Handaxe					= $A0CEE0
	aMapAnim_Silver_DevilAxe			= $A0CFE0
	aMapAnim_Vouge_Poleax				= $A0D0E0
	aMapAnim_BraveAxe					= $A0D1E0
	aMapAnim_UnusedAxe					= $A0D2E0
	aMapAnim_BattleAxe					= $A0D3E0
	aMapAnim_Killer_MasterAxe			= $A0D4E0
	aMapAnim_Bows						= $A0D5E0
	aMapAnim_UnusedBow					= $A0D6E0
	aMapAnim_VeninBow_Shortbow			= $A0D7E0
	aMapAnim_Longbow					= $A0D8E0
	aMapAnim_Greatbow					= $A0D9E0
	aMapAnim_Masterbow					= $A0DAE0
	aMapAnim_BraveBow					= $A0DBE0

;	Map weapon palettes

	MapPalette_Others		= $00
	MapPalette_Brown		= $01
	MapPalette_White		= $02
	MapPalette_Beige		= $03
	MapPalette_Pink			= $04
	MapPalette_Grey			= $05
	MapPalette_Yellow		= $06
	MapPalette_DarkPurple	= $07
	MapPalette_Purple		= $08
	MapPalette_GreyBrown	= $09
	MapPalette_GreyBlue		= $0A
	MapPalette_Green		= $0B
	MapPalette_DarkGreyBlue	= $0C
	MapPalette_Black		= $0D

;	Map spell effects

	MapSpellEffect_None			 = $00
	MapSpellEffect_Fire			 = $01
	MapSpellEffect_Elfire		 = $02
	MapSpellEffect_Bolganone	 = $03
	MapSpellEffect_Valflame		 = $04
	MapSpellEffect_Meteor		 = $05
	MapSpellEffect_Thunder		 = $06
	MapSpellEffect_DireThunder	 = $07
	MapSpellEffect_Thoron		 = $08
	MapSpellEffect_Mjolnir		 = $09
	MapSpellEffect_Bolting		 = $0A
	MapSpellEffect_Wind			 = $0B
	MapSpellEffect_Unused1		 = $0C
	MapSpellEffect_Grafcalibur	 = $0D
	MapSpellEffect_Tornado		 = $0E
	MapSpellEffect_Forseti		 = $0F
	MapSpellEffect_Blizzard		 = $10
	MapSpellEffect_Light		 = $11
	MapSpellEffect_Nosferatu	 = $12
	MapSpellEffect_Aura			 = $13
	MapSpellEffect_Unused2		 = $14
	MapSpellEffect_Jormungand	 = $15
	MapSpellEffect_Fenrir		 = $16
	MapSpellEffect_Hel			 = $17
	MapSpellEffect_Loptous		 = $18
	MapSpellEffect_Heal			 = $19
	MapSpellEffect_Mend			 = $1A
	MapSpellEffect_ReturnStaff	 = $1B
	MapSpellEffect_Recover		 = $1C
	MapSpellEffect_Physic		 = $1D
	MapSpellEffect_Warp			 = $1E
	MapSpellEffect_Restore		 = $1F
	MapSpellEffect_Silence		 = $20
	MapSpellEffect_Sleep		 = $21
	MapSpellEffect_Berserk		 = $22
	MapSpellEffect_Fortify		 = $23
	MapSpellEffect_Rescue		 = $24
	MapSpellEffect_Unused3		 = $25
	MapSpellEffect_Unlock		 = $26
	MapSpellEffect_ThiefStaff	 = $27
	MapSpellEffect_Watch		 = $28
	MapSpellEffect_Unused4		 = $29
	MapSpellEffect_Ballista		 = $2A
	MapSpellEffect_Ensorcel		 = $2B
	MapSpellEffect_Hammerne		 = $2C
	MapSpellEffect_TorchStaff	 = $2D
	MapSpellEffect_Rewarp		 = $2E
	MapSpellEffect_Unused5		 = $2F
	MapSpellEffect_Unused6		 = $30
	MapSpellEffect_Petrify		 = $31
	MapSpellEffect_Venin		 = $32
	MapSpellEffect_Unused7		 = $33
	MapSpellEffect_Kia			 = $34
	
;	Map status effects

	MapStatusEffect_None		 = $00
	MapStatusEffect_Sleep		 = $21
	MapStatusEffect_Berserk		 = $22
	MapStatusEffect_Poison		 = $2F
	MapStatusEffect_Stone		 = $30