.include "ShopPointers.asm"
.include "ArenaPointers.asm"
.include "ChapterNamePointers.asm"
.include "ObjectivePointers.asm"
.include "RankingPointers.asm"
.include "EndingWhitePointers.asm"
.include "EpilogueDescriptionsPointers.asm"
.include "EpilogueTitlesPointers.asm"