* = $7E572 
.logical mapped($7E572)
.long dialogueChapter01Title
.long dialogueChapter02Title
.long dialogueChapter02xTitle
.long dialogueChapter03Title
.long dialogueChapter04Title
.long dialogueChapter04xTitle
.long dialogueChapter05Title
.long dialogueChapter06Title
.long dialogueChapter07Title
.long dialogueChapter08Title
.long dialogueChapter08xTitle
.long dialogueChapter09Title
.long dialogueChapter10Title
.long dialogueChapter11Title
.long dialogueChapter11xTitle
.long dialogueChapter12Title
.long dialogueChapter12xTitle
.long dialogueChapter13Title
.long dialogueChapter14Title
.long dialogueChapter14xTitle
.long dialogueChapter15Title
.long dialogueChapter16ATitle
.long dialogueChapter17ATitle
.long dialogueChapter16BTitle
.long dialogueChapter17BTitle
.long dialogueChapter18Title
.long dialogueChapter19Title
.long dialogueChapter20Title
.long dialogueChapter21Title
.long dialogueChapter21xTitle
.long dialogueChapter22Title
.long dialogueChapter23Title
.long dialogueChapter24Title
.long dialogueChapter24xTitle
.long dialogueChapterFinalTitle
.here